# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.6.0
_src_path: gh:algorandfoundation/algokit-python-template
author_email: abhisathvikreddy1738527@gmail.com
author_name: abhisathvik
contract_name: medical
deployment_language: python
preset_name: starter
project_name: medical-contracts

